### PR TITLE
cleanup and fix bugs for runc and docker factory

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao mashimiao.fnst@cn.fujitsu.com

### CODE REVIEW

**Comment by liangchenye** [comment]
Thanks, I'll review tomorrow.

**Comment by liangchenye** [comment]
@Mashimiao sorry, I don't get time to review it today.
I'll do it before next Wednesday.

**Comment by Mashimiao** [comment]
@liangchenye  OK

**Comment by liangchenye** [comment]
@Mashimiao  'SetRT' do not necessary and 'app' to 'case' makes sense.
LGTM, thanks.

**Pull request merged**
